#!/bin/bash -l
#$ -N wgc.common
#$ -cwd
#$ -S /bin/bash
#$ -V
#$ -q all.q
#$ -l h_vmem=20G
#$ -l s_rt=30:00:00
#$ -pe smp 1
#$ -m a
#$ -M pzhou@caas.cn
#$ -j y
#$ -o jc.out

source activate nf

s=genomes
s=rice
s=maize
s=wheat
s=Laburnicola

cd $wgc/nf
nextflow run $nf/wgc -params-file $proj/genome/nf/config_caas/$s.yml \
    -profile conda,caas -resume

